import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const interTightItalic = localFont({
  src: "./fonts/InterTight-Italic.ttf",
  variable: "--font-intertight-italic",
  weight: "100 900",
});

const interTight = localFont({
  src: "./fonts/InterTight.ttf",
  variable: "--font-intertight",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${interTightItalic.variable} ${interTight.variable}`}>
        {children}
      </body>
    </html>
  );
}
